# GitHub releases will build and publish the package to PyPI with the version of the release.
# Push and manual invocation will only build.

name: Build and publish Python package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          pip install --root-user-action=ignore build

      # Update setup.cfg with the version number of the GitHub release
      - name: Set version number for release build
        if: github.event_name == 'release'
        run: |
          sed -i 's/\$\$REPLACE_IN_WORKFLOW\$\$/${{ github.event.release.tag_name }}/g' setup.cfg

      # For test buildsm use version number 0.0.1
      - name: Set version number for test build
        if: github.event_name != 'release'
        run: |
          sed -i 's/\$\$REPLACE_IN_WORKFLOW\$\$/0.0.1/g' setup.cfg

      - name: Build package
        run: |
          python -m build

      - name: Publish package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
